import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by niggers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-black h-10 z-9999">
          <div className="my-0 mx-auto max-w-screen-lg h-full text-white content-center">
            <ul className="flex w-auto space-x-9 text-xs justify-center">
              <li>Home</li>
              <li>Phone</li>
              <li>Home</li>
              <li>Phone</li>
            </ul>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
